"""Apply hand-assigned codes from open-coding pass to the 150-issue
misclassification sample. Writes scripts/audit/qual/codes_misclass.csv.

Each entry is keyed by (method, project, test_idx). The 'code' column is
the primary categorical code from codebook.md. The 'retrieval_skew' column
is True when the top-12 neighbors had >=7/12 of the wrong-class label.
The 'note' column is a one-line rationale for the code.
"""
from __future__ import annotations
import pandas as pd
from pathlib import Path

BASE = Path(__file__).parent
df = pd.read_csv(BASE / "sample_misclassifications.csv")

# Each entry: (method, proj, test_idx) -> (code, retrieval_skew_bool, note)
CODES: dict[tuple, tuple[str, bool, str]] = {

# === BRAGTAG bug=>X (rows 0-9) ===
("BRAGTAG", "bitcoin_bitcoin", 26): ("BUG-SHAPED-QUESTION", False,
    "User describes app freezing but writes in support style; balanced neighbors."),
("BRAGTAG", "dart-lang_sdk", 20): ("HYBRID-REPORT", False,
    "Reports unwanted UX behavior; reads like a bug or a feature request to change ordering."),
("BRAGTAG", "kubernetes_kubernetes", 51): ("FEATURE-AS-BUG", False,
    "'Informers are not named' is a request for a new naming feature filed as bug."),
("BRAGTAG", "kubernetes_kubernetes", 79): ("LABEL-NOISE", False,
    "Cherry-pick PR for a fix; not really a bug report. 12/12 bug neighbors but predicted feature anyway."),
("BRAGTAG", "microsoft_vscode", 58): ("LABEL-NOISE", False,
    "'Remove xtermTerminal.X' is a refactor/cleanup, not a bug."),
("BRAGTAG", "microsoft_vscode", 66): ("BUG-SHAPED-QUESTION", False,
    "'White on gray is not readable' — short, almost a UX complaint with no repro."),
("BRAGTAG", "microsoft_vscode", 71): ("CLEAN-ERROR", False,
    "Clear bug repro of feature not working; balanced neighbors but predicted question."),
("BRAGTAG", "opencv_opencv", 36): ("LABEL-NOISE", False,
    "Title literally 'feat:' — PR description for adding typing stub. Not a bug."),
("BRAGTAG", "opencv_opencv", 38): ("LABEL-NOISE", False,
    "Patch description ('This patch introduces typings generation') — feature/PR not bug."),
("BRAGTAG", "opencv_opencv", 97): ("BUG-SHAPED-QUESTION", False,
    "User reports an error while doing X but ends with 'help me'; balanced neighbors."),

# === BRAGTAG feature=>X (rows 10-19) ===
("BRAGTAG", "facebook_react", 137): ("HYBRID-REPORT", False,
    "Author hedges 'Cryptic title... Am I misunderstanding?' — feature request mixed with question."),
("BRAGTAG", "facebook_react", 143): ("LABEL-NOISE", False,
    "Author opens 'I want to report a bug' — feature GT contradicts author framing."),
("BRAGTAG", "flutter_flutter", 153): ("BUG-SHAPED-FEATURE", True,
    "'Does not work, it should also disable...' — feature request in bug template; bug-heavy nbrs."),
("BRAGTAG", "microsoft_TypeScript", 116): ("LABEL-NOISE", False,
    "Header literally '# Bug Report'; behavior changed between versions; predicted bug is defensible."),
("BRAGTAG", "microsoft_TypeScript", 143): ("LABEL-NOISE", False,
    "Header '# Bug Report' but the body asks for support routing and discusses workarounds."),
("BRAGTAG", "microsoft_vscode", 110): ("BUG-SHAPED-FEATURE", False,
    "'I'm expecting X' — accessibility enhancement filed in bug-style language."),
("BRAGTAG", "microsoft_vscode", 139): ("BUG-SHAPED-FEATURE", False,
    "'Expected/Unexpected behavior' template; really requesting custom-style support."),
("BRAGTAG", "tensorflow_tensorflow", 162): ("LABEL-NOISE", False,
    "Body asks 'It is not clear...' multiple times — reads as a question/support request."),
("BRAGTAG", "tensorflow_tensorflow", 188): ("HYBRID-REPORT", False,
    "Asks for solution AND requests platform support — question/feature ambiguity."),
("BRAGTAG", "tensorflow_tensorflow", 198): ("LABEL-NOISE", False,
    "Body says 'Issue type: Feature Request' but title is 'How to limit GPU memory...?'"),

# === BRAGTAG question=>X (rows 20-49) ===
("BRAGTAG", "ansible_ansible", 230): ("LABEL-NOISE", False,
    "Cherry-pick PR description; not a question. (Ansible cherry-pick pattern)"),
("BRAGTAG", "ansible_ansible", 271): ("LABEL-NOISE", False, "Cherry-pick PR, not a question."),
("BRAGTAG", "ansible_ansible", 278): ("LABEL-NOISE", False, "Cherry-pick PR, not a question."),
("BRAGTAG", "ansible_ansible", 288): ("LABEL-NOISE", False, "Cherry-pick PR, not a question."),
("BRAGTAG", "ansible_ansible", 292): ("LABEL-NOISE", False, "Cherry-pick PR, not a question."),
("BRAGTAG", "bitcoin_bitcoin", 284): ("LABEL-NOISE", False,
    "Body uses '### Please describe the feature you'd like to see added.' template — feature request, not question."),
("BRAGTAG", "bitcoin_bitcoin", 294): ("HYBRID-REPORT", False,
    "User asks for documentation/installer change — between question and feature."),
("BRAGTAG", "dotnet_roslyn", 210): ("BUG-SHAPED-QUESTION", False,
    "'Steps to reproduce', analyzer failure description — bug template, support-seeking content."),
("BRAGTAG", "dotnet_roslyn", 211): ("BUG-SHAPED-QUESTION", True,
    "Bug template with NullReferenceException; bug-heavy neighbors."),
("BRAGTAG", "dotnet_roslyn", 212): ("BUG-SHAPED-QUESTION", True,
    "'Strange behavior when passing null' with code repro; bug-heavy neighbors."),
("BRAGTAG", "dotnet_roslyn", 228): ("AUTHOR-UNCERTAIN", False,
    "Author opens 'I have no idea what I'm doing... my apologies if this isn't actually a bug'."),
("BRAGTAG", "dotnet_roslyn", 248): ("HYBRID-REPORT", False,
    "Source-generator design discussion — feature/question hybrid."),
("BRAGTAG", "dotnet_roslyn", 252): ("BUG-SHAPED-QUESTION", True,
    "'CS8604 Compiler Warning despite null checking' — bug template; bug-heavy neighbors."),
("BRAGTAG", "dotnet_roslyn", 274): ("BUG-SHAPED-QUESTION", False,
    "'IncrementalGenerator caches X too aggressively' — bug-style; bug-heavy neighbors."),
("BRAGTAG", "dotnet_roslyn", 289): ("BUG-SHAPED-QUESTION", False,
    "'parses incorrectly when chained' — bug-style title; bug-heavy reasoning."),
("BRAGTAG", "dotnet_roslyn", 294): ("HYBRID-REPORT", False,
    "Discusses DoesNotReturn attribute behavior — design question/feature request."),
("BRAGTAG", "facebook_react", 210): ("BUG-SHAPED-QUESTION", True,
    "'Bug' literally in body, command fails with stack trace; 12/12 bug neighbors."),
("BRAGTAG", "facebook_react", 257): ("BUG-SHAPED-QUESTION", True,
    "'Webpack can't find X' but author hedges 'is it me doing something wrong'; 12/12 bug nbrs."),
("BRAGTAG", "facebook_react", 295): ("BUG-SHAPED-QUESTION", True,
    "Reports broken extension behavior; bug-heavy neighbors."),
("BRAGTAG", "flutter_flutter", 205): ("BUG-SHAPED-QUESTION", False,
    "Permission denied error report; uses bug template (template encourages SO redirect for questions)."),
("BRAGTAG", "microsoft_TypeScript", 225): ("LABEL-NOISE", False,
    "Header '# Bug Report' explicitly; 'v5 beta typescript support not working' — bug template."),
("BRAGTAG", "microsoft_TypeScript", 230): ("LABEL-NOISE", False,
    "'[request]' in title; '# Suggestion' template — feature request, not question."),
("BRAGTAG", "microsoft_TypeScript", 261): ("LABEL-NOISE", False,
    "Header '# Bug Report'; 'TS2488 -- for of method...' — bug template."),
("BRAGTAG", "microsoft_vscode", 230): ("LABEL-NOISE", False,
    "Body uses 'feature_request_template' explicitly; predicted feature is correct."),
("BRAGTAG", "microsoft_vscode", 266): ("LABEL-NOISE", False,
    "'feature_request_template' in body; user asks for window-title behavior."),
("BRAGTAG", "opencv_opencv", 226): ("BUG-SHAPED-QUESTION", False,
    "'Cannot build' — system info template; build issue is bug-shaped."),
("BRAGTAG", "opencv_opencv", 263): ("LABEL-NOISE", False,
    "Author explicitly checks 'I report the issue, it's not a question'."),
("BRAGTAG", "tensorflow_tensorflow", 232): ("BUG-SHAPED-QUESTION", False,
    "RuntimeError stack trace report — bug template, support-seeking."),
("BRAGTAG", "tensorflow_tensorflow", 244): ("BUG-SHAPED-QUESTION", False,
    "TfLite GPU delegate failure — bug-template error report."),
("BRAGTAG", "tensorflow_tensorflow", 259): ("BUG-SHAPED-QUESTION", False,
    "'tensorflow.map hangs randomly' — bug template; bug-heavy neighbors."),

# === FT bug=>X (rows 50-59) ===
("FT", "bitcoin_bitcoin", 336): ("LABEL-NOISE", False,
    "Discussion of systemd network target choice — design/feature request, not bug."),
("FT", "bitcoin_bitcoin", 367): ("AUTHOR-UNCERTAIN", False,
    "Author writes 'it seems a bug but also future request'."),
("FT", "dart-lang_sdk", 612): ("LABEL-NOISE", False,
    "Reports test failures resulting from a CL — looks like a tracking issue, not a true bug."),
("FT", "flutter_flutter", 1571): ("FEATURE-AS-BUG", False,
    "'Tell users the exact widget type (will PR)' — clear feature/enhancement."),
("FT", "kubernetes_kubernetes", 1818): ("HYBRID-REPORT", False,
    "Multi-arch image broken — bug + 'please give us multiarch image' (request)."),
("FT", "kubernetes_kubernetes", 1859): ("CLEAN-ERROR", False,
    "Clear bug template with repro; FT chose question with no obvious confound."),
("FT", "microsoft_vscode", 2415): ("FEATURE-AS-BUG", False,
    "'Should be created under...' — feature request for default behavior change."),
("FT", "microsoft_vscode", 2463): ("FEATURE-AS-BUG", False,
    "'Make max comment area height depend on...' — feature/UX enhancement."),
("FT", "opencv_opencv", 2717): ("LABEL-NOISE", False,
    "PR description ('Pull Request Readiness Checklist...') — not a bug report."),
("FT", "tensorflow_tensorflow", 3079): ("LABEL-NOISE", False,
    "Body explicitly: 'Issue type: Feature Request' — predicted feature is correct."),

# === FT feature=>X (rows 60-69) ===
("FT", "dart-lang_sdk", 797): ("BUG-SHAPED-FEATURE", False,
    "'Fix appears in locations where it is not available' — UX bug-feature blend."),
("FT", "dotnet_roslyn", 1013): ("BUG-SHAPED-FEATURE", False,
    "'Copying out of raw string results in indented' — describes existing limitation."),
("FT", "dotnet_roslyn", 1076): ("LABEL-NOISE", False,
    "Author opens 'this is not a proposal but a question'."),
("FT", "facebook_react", 1372): ("LABEL-NOISE", False,
    "Author tags 'Bug/unexpected behavior'; GT=feature contradicts author."),
("FT", "flutter_flutter", 1676): ("LABEL-NOISE", False,
    "'Fixes #126297' — PR description, not a feature request."),
("FT", "microsoft_TypeScript", 2222): ("LABEL-NOISE", False,
    "Header '# Bug Report' — bug-template, predicted bug is reasonable."),
("FT", "microsoft_TypeScript", 2266): ("LABEL-NOISE", False,
    "Header '# Bug Report' — author tags as bug, GT contradicts."),
("FT", "opencv_opencv", 2845): ("BUG-SHAPED-FEATURE", False,
    "'CANN graph check failed' compile error — looks fully like a bug."),
("FT", "tensorflow_tensorflow", 3146): ("BUG-SHAPED-FEATURE", False,
    "'Issue Type: Documentation Bug' header but content asks for int16 support — feature."),
("FT", "tensorflow_tensorflow", 3154): ("BUG-SHAPED-FEATURE", False,
    "'protobuf 4 is not supported' filed in TF bug template; really a feature request."),

# === FT question=>X (rows 70-99) ===
("FT", "ansible_ansible", 258): ("BUG-SHAPED-QUESTION", False,
    "'Issue Type: Bug Report' template explicitly; user asks for help with config."),
("FT", "ansible_ansible", 263): ("LABEL-NOISE", False,
    "Body is a maintainer's quote-comment; not really an issue."),
("FT", "ansible_ansible", 271): ("LABEL-NOISE", False, "Cherry-pick PR (Ansible pattern)."),
("FT", "bitcoin_bitcoin", 598): ("BUG-SHAPED-QUESTION", False,
    "'Sign and verify message not working!' — bug template, signing question."),
("FT", "dart-lang_sdk", 825): ("BUG-SHAPED-QUESTION", False,
    "'No warning for X used incorrectly?' — language analyzer support request in bug shape."),
("FT", "dart-lang_sdk", 857): ("BUG-SHAPED-QUESTION", False,
    "'RegExp hang' — terse bug-style report."),
("FT", "dotnet_roslyn", 1136): ("BUG-SHAPED-QUESTION", False,
    "'.editorconfig... affects non-constant symbols' — bug-style description."),
("FT", "dotnet_roslyn", 1190): ("BUG-SHAPED-QUESTION", False,
    "'False positive CS0165' — sounds like a clear compiler bug."),
("FT", "facebook_react", 1403): ("HYBRID-REPORT", False,
    "Author opens 'this was me toying around... I don't know what these can be used for'."),
("FT", "facebook_react", 1444): ("HYBRID-REPORT", False,
    "Translation complaint — bug or feature request, not really a question."),
("FT", "facebook_react", 1446): ("LABEL-NOISE", False,
    "Title 'Bug: useRef can not return...'; 'Steps to Reproduce' template — bug, not question."),
("FT", "flutter_flutter", 1716): ("BUG-SHAPED-QUESTION", False,
    "'Container with strict size expanding to parent size' — bug-style report from a confused dev."),
("FT", "flutter_flutter", 1760): ("HYBRID-REPORT", False,
    "Asks for alternative to a removed property — question/feature mix."),
("FT", "flutter_flutter", 1788): ("BUG-SHAPED-QUESTION", False,
    "'statusBarIconBrightness is not working' — bug template, version-specific question."),
("FT", "flutter_flutter", 1794): ("BUG-SHAPED-QUESTION", False,
    "'Click events failing' — bug-style narrative, asks for help."),
("FT", "flutter_flutter", 1798): ("BUG-SHAPED-QUESTION", False,
    "'TwoDimensionalScrollView RenderFlex issue' — bug template, dev asks why."),
("FT", "kubernetes_kubernetes", 2005): ("BUG-SHAPED-QUESTION", False,
    "'Kubernetes instability issues' — bug-template support request."),
("FT", "kubernetes_kubernetes", 2027): ("BUG-SHAPED-QUESTION", False,
    "'kubelet.service: Main process exited' — bug template, kubeadm setup support."),
("FT", "microsoft_TypeScript", 2337): ("LABEL-NOISE", False,
    "Body uses '# Suggestion' / 'Viability Checklist' — feature request, not question."),
("FT", "microsoft_TypeScript", 2347): ("BUG-SHAPED-QUESTION", False,
    "Header '# Bug Report'; 'Could not resolve' enum from .d.ts — clear bug template."),
("FT", "microsoft_TypeScript", 2387): ("BUG-SHAPED-QUESTION", False,
    "'Rename autofix introduces errors' — bug template, IDE feature support."),
("FT", "microsoft_vscode", 2600): ("BUG-SHAPED-QUESTION", False,
    "'Unable to record in user setting' — auto-bug template; user asks for help with settings."),
("FT", "microsoft_vscode", 2612): ("BUG-SHAPED-QUESTION", False,
    "'Type: Bug' template — user asks basic Python install question; FT regurgitates prompt template."),
("FT", "microsoft_vscode", 2653): ("BUG-SHAPED-QUESTION", False,
    "'Type: Bug' — basic C compile question via bug template; FT regurgitates."),
("FT", "microsoft_vscode", 2673): ("BUG-SHAPED-QUESTION", False,
    "'Type: Bug' — basic C++ logic question via VSCode auto-bug template."),
("FT", "microsoft_vscode", 2688): ("BUG-SHAPED-QUESTION", False,
    "'Type: Bug' — terminal cwd question; user explicitly asks 'How do we solve...'"),
("FT", "opencv_opencv", 2951): ("BUG-SHAPED-QUESTION", False,
    "'Unable to compile 4.5.5 with ARM' — system-info bug template, build support request."),
("FT", "opencv_opencv", 2952): ("BUG-SHAPED-QUESTION", False,
    "'OpenCV 4.7 cuda 12.0 VS22 lnk2019 error' — bug template, build support."),
("FT", "opencv_opencv", 2991): ("BUG-SHAPED-QUESTION", False,
    "'Cross compiling ARM64 in Windows fails' — bug template, build support."),
("FT", "tensorflow_tensorflow", 3257): ("BUG-SHAPED-QUESTION", False,
    "'Same error as #35100' — error reproduction in bug-shape."),

# === RAGTAG bug=>X (rows 100-109) ===
("RAGTAG", "bitcoin_bitcoin", 40): ("HYBRID-REPORT", False,
    "Bug + author proposes a fix at the end."),
("RAGTAG", "bitcoin_bitcoin", 64): ("CLEAN-ERROR", True,
    "Clear bug template (Expected/Actual); 10/12 question neighbors pulled prediction."),
("RAGTAG", "dotnet_roslyn", 31): ("HYBRID-REPORT", False,
    "'Fuzz test the incremental state table' — proposes a testing infra feature; predicted feature reasonable."),
("RAGTAG", "dotnet_roslyn", 47): ("CLEAN-ERROR", True,
    "RPS failure stack trace — bug; 9/12 question neighbors misled prediction."),
("RAGTAG", "facebook_react", 95): ("QUESTION-SHAPED-OTHER", False,
    "Title says 'Bug' but body is all 'Is there any information... what is the future...'"),
("RAGTAG", "kubernetes_kubernetes", 18): ("HYBRID-REPORT", True,
    "Multiarch image broken + 'please give us...' request; 12/12 question neighbors."),
("RAGTAG", "microsoft_TypeScript", 70): ("LABEL-NOISE", False,
    "Tracking issue '`lib.d.ts` Updates for TypeScript 5.3' — meta-issue, not really a bug."),
("RAGTAG", "microsoft_TypeScript", 81): ("BUG-SHAPED-QUESTION", True,
    "'Type inference changed' — bug-template but reads like asking why; 10/12 question nbrs."),
("RAGTAG", "microsoft_vscode", 64): ("HYBRID-REPORT", False,
    "Reports unexpected UI multi-select; could go bug or feature."),
("RAGTAG", "opencv_opencv", 38): ("LABEL-NOISE", False,
    "PR description / patch description — not a bug."),

# === RAGTAG feature=>X (rows 110-119) ===
("RAGTAG", "bitcoin_bitcoin", 142): ("BUG-SHAPED-FEATURE", False,
    "Namespacing macro design issue framed bug-style; really a refactor/feature."),
("RAGTAG", "dotnet_roslyn", 153): ("LABEL-NOISE", False,
    "Title literally 'Which commit corresponds to 4.4.0?' — clear question."),
("RAGTAG", "flutter_flutter", 147): ("BUG-SHAPED-FEATURE", True,
    "'Doctor advises invalid command' — bug template; really a UX/feature fix; 9/12 bug nbrs."),
("RAGTAG", "microsoft_vscode", 127): ("BUG-SHAPED-FEATURE", True,
    "'Menu bar unnecessarily changes...' — feature/UX request in bug style; 8/12 bug nbrs."),
("RAGTAG", "microsoft_vscode", 145): ("BUG-SHAPED-FEATURE", True,
    "'Should have half the contrast ratio' — feature-style 'should' phrased as bug; 10/12 bug nbrs."),
("RAGTAG", "microsoft_vscode", 166): ("BUG-SHAPED-FEATURE", True,
    "'testing.openTesting is not working' — feature request to extend behavior; 8/12 bug nbrs."),
("RAGTAG", "tensorflow_tensorflow", 102): ("LABEL-NOISE", False,
    "Title 'How to build...' literally a question; balanced neighbors."),
("RAGTAG", "tensorflow_tensorflow", 127): ("LABEL-NOISE", False,
    "'How to build TensorFlow from source with Clang?' — literally a question."),
("RAGTAG", "tensorflow_tensorflow", 157): ("LABEL-NOISE", True,
    "'Issue Type: Bug' header — predicted bug consistent with author tag; 7/12 bug nbrs."),
("RAGTAG", "tensorflow_tensorflow", 192): ("LABEL-NOISE", False,
    "'Issue Type: Support' header — predicted question consistent with body."),

# === RAGTAG question=>X (rows 120-149) ===
("RAGTAG", "ansible_ansible", 228): ("BUG-SHAPED-QUESTION", False,
    "'ios_config diff_against not applying' — Ansible bug template, but seeking help."),
("RAGTAG", "ansible_ansible", 229): ("LABEL-NOISE", False, "Cherry-pick PR (Ansible pattern)."),
("RAGTAG", "ansible_ansible", 230): ("LABEL-NOISE", False, "Cherry-pick PR (Ansible pattern)."),
("RAGTAG", "ansible_ansible", 278): ("LABEL-NOISE", False, "Cherry-pick PR (Ansible pattern)."),
("RAGTAG", "ansible_ansible", 285): ("LABEL-NOISE", False, "Cherry-pick PR (Ansible pattern)."),
("RAGTAG", "bitcoin_bitcoin", 253): ("BUG-SHAPED-QUESTION", True,
    "'SQLite version vulnerability' — security concern; 8/12 bug nbrs."),
("RAGTAG", "bitcoin_bitcoin", 279): ("BUG-SHAPED-QUESTION", False,
    "'Method not found' — short bug-shaped report, possibly a question."),
("RAGTAG", "dart-lang_sdk", 273): ("BUG-SHAPED-QUESTION", False,
    "'Analyzer - cannot get right type' — debugging assistance request."),
("RAGTAG", "dotnet_roslyn", 208): ("BUG-SHAPED-QUESTION", False,
    "Concurrency / data race report — bug template; predicted bug reasonable."),
("RAGTAG", "facebook_react", 200): ("BUG-SHAPED-QUESTION", False,
    "Author tags 'issue type: bug' in body — predicted bug consistent."),
("RAGTAG", "facebook_react", 226): ("AUTHOR-UNCERTAIN", False,
    "'I'm not really sure if it is a bug or not' — explicit hedge."),
("RAGTAG", "facebook_react", 284): ("LABEL-NOISE", False,
    "Title 'Bug: 17.0.1 npm packages...' — author tags bug; predicted bug consistent."),
("RAGTAG", "facebook_react", 290): ("LABEL-NOISE", False,
    "Title 'Bug: useEffect happens synchronously...' — author tags bug."),
("RAGTAG", "flutter_flutter", 216): ("BUG-SHAPED-QUESTION", False,
    "Container size question filed in bug shape (no template), seeking help."),
("RAGTAG", "flutter_flutter", 280): ("HYBRID-REPORT", False,
    "Asks how-to + proposes API change — question/feature mix."),
("RAGTAG", "flutter_flutter", 298): ("BUG-SHAPED-QUESTION", False,
    "'TwoDimensional RenderFlex issue' — bug template, dev asks why."),
("RAGTAG", "kubernetes_kubernetes", 203): ("BUG-SHAPED-QUESTION", True,
    "Calico failure with K8s — bug template; 10/12 question nbrs but predicted bug anyway."),
("RAGTAG", "kubernetes_kubernetes", 219): ("HYBRID-REPORT", False,
    "Maintainer of related project asks about resource scoping — feature/question hybrid."),
("RAGTAG", "kubernetes_kubernetes", 252): ("BUG-SHAPED-QUESTION", True,
    "'helm upgrade causing downtime' — bug template, support request; 7/12 bug nbrs."),
("RAGTAG", "kubernetes_kubernetes", 259): ("BUG-SHAPED-QUESTION", False,
    "'Traffic to unready pod' — bug template, asks for help."),
("RAGTAG", "kubernetes_kubernetes", 294): ("BUG-SHAPED-QUESTION", True,
    "Body literally '**This is a Bug Report**'; 10/12 question nbrs but predicted bug."),
("RAGTAG", "microsoft_TypeScript", 218): ("LABEL-NOISE", False,
    "Header '# Bug Report'; behavior changed between TS versions — bug template."),
("RAGTAG", "microsoft_TypeScript", 253): ("LABEL-NOISE", False,
    "Body uses 'feature_request_template' explicitly; predicted feature is correct."),
("RAGTAG", "microsoft_TypeScript", 254): ("LABEL-NOISE", False,
    "Header '# Bug Report' — bug template; predicted bug."),
("RAGTAG", "microsoft_TypeScript", 258): ("LABEL-NOISE", False,
    "Header '# Bug Report' — bug template; predicted bug consistent with author."),
("RAGTAG", "opencv_opencv", 265): ("BUG-SHAPED-QUESTION", False,
    "'Cannot load TensorFlow SavedModel' — opencv bug template; build/integration support."),
("RAGTAG", "opencv_opencv", 296): ("BUG-SHAPED-QUESTION", False,
    "'Installing opencv breaks pytorch' — bug template; environment support."),
("RAGTAG", "opencv_opencv", 299): ("BUG-SHAPED-QUESTION", False,
    "'Memory overflow' — bug template; OOM debugging."),
("RAGTAG", "tensorflow_tensorflow", 262): ("BUG-SHAPED-QUESTION", False,
    "RESHAPE op compatibility — bug-template language, predicted bug consistent."),
("RAGTAG", "tensorflow_tensorflow", 299): ("LABEL-NOISE", False,
    "'ADD support for VEDV' — feature request template, predicted feature correct."),
}

# Verify completeness
expected = set(zip(df["__method"], df["__proj"], df["test_idx"]))
got = set(CODES.keys())
missing = expected - got
extra = got - expected
if missing:
    print(f"WARNING: missing {len(missing)} keys:")
    for k in sorted(missing): print(f"  {k}")
if extra:
    print(f"WARNING: extra {len(extra)} keys:")
    for k in sorted(extra): print(f"  {k}")

# Build output
rows = []
for _, r in df.iterrows():
    key = (r["__method"], r["__proj"], int(r["test_idx"]))
    code, ret_skew, note = CODES.get(key, ("OTHER", False, "MISSING"))
    rows.append({
        "method": r["__method"], "project": r["__proj"], "test_idx": int(r["test_idx"]),
        "ground_truth": r["ground_truth"], "predicted_label": r["predicted_label"],
        "code": code, "retrieval_skew": ret_skew, "note": note,
    })
out = pd.DataFrame(rows)
out.to_csv(BASE / "codes_misclass.csv", index=False)
print(f"wrote {BASE / 'codes_misclass.csv'} ({len(out)} rows)")
print(f"\ncode distribution:")
print(out["code"].value_counts())
print(f"\ncode x method:")
print(pd.crosstab(out["code"], out["method"]))
print(f"\nretrieval-skew rate by method:")
print(out.groupby("method")["retrieval_skew"].mean().round(2))
