"""docs/reframe/NUMBERS.md -- every number the paper's prose may quote, in the paper's format.

Scores (macro/per-class F1, P, R) are percent with one decimal; differences between
methods are percentage points ("points") with one decimal; shares and error rates are
whole percent with the one-decimal value in brackets so boundary cases are visible.
Every range (min-max over the four model sizes) is taken over exact values and only
then rounded; never quote a difference computed from rounded values.

Inputs (all committed, so this runs on any machine):
  paper/tables/triangulation_all_cells.csv  every (method, setting, model, k) cell
  paper/tables/method_comparison_ci.csv     paired-bootstrap differences vs PA fine-tuning
  paper/tables/fallback_macro_f1.csv        macro F1 with the kNN-voting fallback (3 d.p.)
  paper/tables/per_project_diff.csv         heatmap data (hand-seeded at 3 d.p.)
  SANER2027/tables/method_cost.tex          peak GPU memory (GB) and times (h), parsed
Values the CSVs do not hold (taken from the draft text) are marked "from the draft".
"""
from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

import pandas as pd

from _figstyle import MODELS

REPO = Path(__file__).resolve().parents[2]
TABLES = REPO / "paper" / "tables"
CELLS = TABLES / "triangulation_all_cells.csv"
CI = TABLES / "method_comparison_ci.csv"
FALLBACK = TABLES / "fallback_macro_f1.csv"
PER_PROJECT = TABLES / "per_project_diff.csv"
COST = REPO / "SANER2027" / "tables" / "method_cost.tex"
OUT = REPO / "docs" / "reframe" / "NUMBERS.md"

NAMES = {"votag": "kNN voting", "zero_shot": "Zero-shot", "ragtag": "RAG",
         "bragtag": "Filtered RAG", "finetune": "Fine-tuning"}
SHORT = [m.replace("Qwen-", "") for m in MODELS]  # 3B, 7B, 14B, 32B
KS = [1, 3, 6, 9, 12, 15]


# ---------------------------------------------------------------- formatting
def pct(x: float) -> str:
    """Score in percent, one decimal."""
    return f"{100 * x:.1f}"


def pts(d: float) -> str:
    """Difference in points, one decimal, signed (the sheet only; prose uses words)."""
    v = round(100 * d, 1)
    return f"{v:+.1f}".replace("+0.0", "0.0").replace("-0.0", "0.0").replace("-", "−")


def share(x: float) -> str:
    """Share or error rate: whole percent, exact one-decimal value in brackets."""
    return f"{100 * x:.0f}% ({100 * x:.1f})"


def rng(values, f=pct, unit="") -> str:
    """min-max over exact values, then rounded."""
    lo, hi = min(values), max(values)
    a, b = f(lo), f(hi)
    return (a if a == b else f"{a}–{b}") + unit


def srng(values) -> str:
    lo, hi = min(values), max(values)
    a, b = f"{100 * lo:.0f}", f"{100 * hi:.0f}"
    return (f"{a}%" if a == b else f"{a}–{b}%") + f" ({100 * lo:.1f}–{100 * hi:.1f})"


def prng(values) -> str:
    """Range of signed differences in points."""
    return rng(values, pts)


def mean(values):
    values = list(values)
    return sum(values) / len(values)


# ---------------------------------------------------------------- data access
cells = pd.read_csv(CELLS)
cells["kk"] = pd.to_numeric(cells.k.replace("-", "-1"), errors="coerce").astype(int)


def cell(method, setting, model, k=None):
    q = cells[(cells.method == method) & (cells.setting == setting) & (cells.model == model)]
    if k is not None:
        q = q[q.kk == k]
    assert len(q) == 1, (method, setting, model, k, len(q))
    return q.iloc[0]


def best(method, setting, model):
    """Highest macro F1 on the grid (same rule as tab_results_master.best_configs)."""
    q = cells[(cells.method == method) & (cells.setting == setting) & (cells.model == model)]
    return q.sort_values("f1_macro", ascending=False).iloc[0]


def zs(model):
    return cell("zero_shot", "PA", model)


def B(method, model):  # the configurations the paper compares
    setting = "PA" if method == "ftpa" else "PS"
    method = "finetune" if method in ("ftpa", "ftps") else method
    return best(method, setting, model)


def ftps(m): return best("finetune", "PS", m)
def ftpa(m): return best("finetune", "PA", m)
def rag(m): return best("ragtag", "PS", m)
def frag(m): return best("bragtag", "PS", m)


def kstr(r):
    return "–" if r.kk < 0 else str(r.kk)


# ---------------------------------------------------------------- sections
L: list[str] = []
P = L.append


def header():
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    P("# NUMBERS: the paper's numbers in the new format")
    P("")
    P(f"Generated by `scripts/paper/numbers_sheet.py` on {now}. Do not edit by hand; rerun the script.")
    P("Sources: `paper/tables/triangulation_all_cells.csv`, `paper/tables/method_comparison_ci.csv`,")
    P("`paper/tables/fallback_macro_f1.csv`, `paper/tables/per_project_diff.csv`, and the GB/hour values")
    P("parsed from `SANER2027/tables/method_cost.tex`.")
    P("")
    P("Format: scores are percent with one decimal (76.7 = 76.7%). Differences are percentage points")
    P("(points) with one decimal; signs appear only in this sheet (+ = the first-named method is ahead),")
    P("prose says \"ahead\"/\"behind\". Shares and error rates are whole percent with the exact value in")
    P("brackets. Ranges are min–max over the four model sizes, taken over exact values, then rounded.")
    P("\"Best\" = highest pooled macro F1 on the method's grid (the rule of `tab_results_master.py`).")
    P("Values marked **from the draft** are not in the CSVs and were copied from the draft text.")
    P("")


def sec_best():
    P("## 1. Best configurations")
    P("")
    P("| Method | Model | k | Macro F1 | P mac | R mac | Bug P | Bug R | Feat P | Feat R | Q P | Q R | "
      "Bug F1 | Feat F1 | Q F1 | Invalid % | Pred. bug share | Q→bug | Q→feat |")
    P("|" + "---|" * 19)
    rows = [("votag", "PS", "-"), ("votag", "PA", "-")]
    for m in MODELS:
        rows += [("zero_shot", "PA", m), ("ragtag", "PS", m), ("ragtag", "PA", m), ("bragtag", "PS", m),
                 ("finetune", "PS", m), ("finetune", "PA", m)]
    for method, setting, m in rows:
        r = best(method, setting, m)
        name = NAMES[method] + ("" if method == "zero_shot" else f" ({setting})")
        P(f"| {name} | {m if m != '-' else '–'} | {kstr(r)} | **{pct(r.f1_macro)}** | {pct(r.p_macro)} | "
          f"{pct(r.r_macro)} | {pct(r.p_bug)} | {pct(r.r_bug)} | {pct(r.p_feature)} | {pct(r.r_feature)} | "
          f"{pct(r.p_question)} | {pct(r.r_question)} | {pct(r.f1_bug)} | {pct(r.f1_feature)} | "
          f"{pct(r.f1_question)} | {100 * r.invalid_rate:.1f} | {share(r.share_bug)} | "
          f"{share(r.conf_question_to_bug)} | {share(r.conf_question_to_feature)} |")
    P("")
    P("Ranges over the four sizes (macro F1, %):")
    P("")
    for label, fn in (("Zero-shot", zs), ("RAG (PS, best k)", rag), ("RAG (PA, best k)",
                      lambda m: best("ragtag", "PA", m)), ("Filtered RAG (PS, best k)", frag),
                      ("Fine-tuning (PS)", ftps), ("Fine-tuning (PA)", ftpa)):
        vals = [fn(m) for m in MODELS]
        P(f"- {label}: {rng([v.f1_macro for v in vals])} "
          f"(per size {', '.join(pct(v.f1_macro) for v in vals)}; best k {'/'.join(kstr(v) for v in vals)})")
    P("")


def sec_rq1():
    P("## 2. RQ1 (RAG)")
    P("")
    z = [zs(m) for m in MODELS]
    P(f"- Zero-shot macro F1: {rng([r.f1_macro for r in z])}%.")
    vps, vpa = best("votag", "PS", "-"), best("votag", "PA", "-")
    for name, v in (("PS", vps), ("PA", vpa)):
        P(f"- kNN voting peak ({name}): {pct(v.f1_macro)}% at k = {v.kk}; macro P {pct(v.p_macro)}, "
          f"macro R {pct(v.r_macro)}; bug P {pct(v.p_bug)}, bug R {pct(v.r_bug)}; "
          f"Q→bug {share(v.conf_question_to_bug)}, Q→feature {share(v.conf_question_to_feature)}.")
    vps_all = cells[(cells.method == "votag") & (cells.setting == "PS")].set_index("kk")
    vpa_all = cells[(cells.method == "votag") & (cells.setting == "PA")].set_index("kk")
    common = sorted(set(vps_all.index) & set(vpa_all.index))
    pa_higher = sum(vpa_all.loc[k].f1_macro > vps_all.loc[k].f1_macro for k in common)
    P(f"- kNN voting PA > PS in macro F1 at {pa_higher} of {len(common)} evaluated k "
      f"(k = {common[0]}..{common[-1]} as in the grid).")
    q_lowest = all(min(r.f1_bug, r.f1_feature, r.f1_question) == r.f1_question
                   for _, r in cells[cells.method == "votag"].iterrows())
    bug_over = all(r.r_bug > r.p_bug for _, r in cells[cells.method == "votag"].iterrows())
    P(f"- kNN voting: question has the lowest class F1 at every k in both settings: {q_lowest}; "
      f"bug recall > bug precision at every k: {bug_over}.")
    P("- kNN voting: PS and PA share 84–90% of their top-k neighbors for k in 3..30 — **from the draft**.")
    P("")
    # 48 configurations
    top_v = cells[cells.method == "votag"]
    vmax = {c: top_v[c].max() for c in ("f1_macro", "p_macro", "r_macro")}
    vbest = vpa  # strongest configuration by macro F1
    n = 0
    beats = {"zs": [0, 0, 0], "vbest": [0, 0, 0], "vmax": [0, 0, 0]}
    for m in MODELS:
        for s in ("PS", "PA"):
            for k in KS:
                r = cell("ragtag", s, m, k)
                n += 1
                for i, c in enumerate(("f1_macro", "p_macro", "r_macro")):
                    beats["zs"][i] += r[c] > zs(m)[c]
                    beats["vbest"][i] += r[c] > vbest[c]
                    beats["vmax"][i] += r[c] > vmax[c]
    P(f"- Nonzero-k RAG configurations (4 sizes × 2 settings × 6 k): {n}. Beating their own zero-shot in "
      f"macro F1/P/R: {beats['zs'][0]}/{beats['zs'][1]}/{beats['zs'][2]}. Beating the best kNN voting "
      f"configuration (PA, k = 16) in F1/P/R: {beats['vbest'][0]}/{beats['vbest'][1]}/{beats['vbest'][2]}. "
      f"Beating the maximum of each metric over all kNN voting cells: "
      f"{beats['vmax'][0]}/{beats['vmax'][1]}/{beats['vmax'][2]}.")
    ps_gt = sum(cell("ragtag", "PS", m, k).f1_macro > cell("ragtag", "PA", m, k).f1_macro
                for m in MODELS for k in KS)
    P(f"- RAG PS > PA in macro F1 at {ps_gt} of 24 (model, k ≥ 1) pairs.")
    rs = [rag(m) for m in MODELS]
    P(f"- RAG (PS) best k: {'/'.join(kstr(r) for r in rs)}; macro F1 {rng([r.f1_macro for r in rs])}%.")
    gains = [rag(m).f1_macro - zs(m).f1_macro for m in MODELS]
    P(f"- RAG best k minus zero-shot: {', '.join(pts(g) for g in gains)} points; mean {pts(mean(gains))}; "
      f"range {prng(gains)}.")
    up = [(m, pts(cell('ragtag', 'PS', m, 15).f1_macro - cell('ragtag', 'PS', m, 12).f1_macro)) for m in MODELS]
    P(f"- RAG PS k = 15 minus k = 12: {', '.join(f'{m} {d}' for m, d in up)} points "
      f"(any improvement: {any(cell('ragtag', 'PS', m, 15).f1_macro > cell('ragtag', 'PS', m, 12).f1_macro for m in MODELS)}).")
    q_low_rag = all(min(r.f1_bug, r.f1_feature, r.f1_question) == r.f1_question
                    for _, r in cells[cells.method.isin(["ragtag", "zero_shot"])].iterrows())
    q_lowR = all(min(r.r_bug, r.r_feature, r.r_question) == r.r_question
                 for _, r in cells[cells.method.isin(["ragtag", "zero_shot"])].iterrows())
    q_lowP = any(min(r.p_bug, r.p_feature, r.p_question) == r.p_question
                 for _, r in cells[cells.method.isin(["ragtag", "zero_shot"])].iterrows())
    P(f"- RAG and zero-shot: question has the lowest F1 in every cell: {q_low_rag}; lowest recall in every "
      f"cell: {q_lowR}; lowest precision in any cell: {q_lowP}.")
    P(f"- Q→bug: zero-shot {srng([r.conf_question_to_bug for r in z])}; RAG best k "
      f"{srng([r.conf_question_to_bug for r in rs])}.")
    P(f"- Q→feature: zero-shot {srng([r.conf_question_to_feature for r in z])}; RAG best k "
      f"{srng([r.conf_question_to_feature for r in rs])}.")
    for name, fn in (("zero-shot", zs), ("RAG best k", rag)):
        P(f"- Averaged over the four sizes, {name}: predicted bug share "
          f"{share(mean(fn(m).share_bug for m in MODELS))}, bug precision "
          f"{pct(mean(fn(m).p_bug for m in MODELS))}%, question recall {pct(mean(fn(m).r_question for m in MODELS))}%.")
    frac = [((rag(m).f1_question - zs(m).f1_question) / 3) / (rag(m).f1_macro - zs(m).f1_macro) for m in MODELS]
    P(f"- Share of the macro-F1 gain (RAG best k over zero-shot) that comes from question F1 "
      f"(Δ question F1 / 3 ÷ Δ macro F1): {', '.join(f'{100 * f:.1f}%' for f in frac)}; range "
      f"{100 * min(frac):.0f}–{100 * max(frac):.0f}%.")
    fb = [r.conf_question_to_bug / (r.conf_question_to_bug + r.conf_feature_to_bug) for r in z]
    fbr = [r.conf_question_to_bug / (r.conf_question_to_bug + r.conf_feature_to_bug) for r in rs]
    P(f"- Fraction of false bug predictions that are true questions (equal class supports): zero-shot "
      f"{srng(fb)}, mean {share(mean(fb))}; RAG best k {srng(fbr)}.")
    P("")


def sec_rq2():
    P("## 3. RQ2 (filtered RAG)")
    P("")
    P("Filtered RAG minus RAG (PS) at each k, points:")
    P("")
    P("| Model | " + " | ".join(f"k={k}" for k in KS) + " |")
    P("|---|" + "---|" * len(KS))
    ge6, le3 = [], []
    for m in MODELS:
        d = {k: cell("bragtag", "PS", m, k).f1_macro - cell("ragtag", "PS", m, k).f1_macro for k in KS}
        ge6 += [d[k] for k in KS if k >= 6]
        le3 += [d[k] for k in KS if k <= 3]
        P(f"| {m} | " + " | ".join(pts(d[k]) for k in KS) + " |")
    P("")
    P(f"- Minimum difference at k ≥ 6: {pts(min(ge6))} (all positive: {min(ge6) > 0}). At k ≤ 3: range "
      f"{prng(le3)}; largest shortfall {pts(min(le3))}.")
    d = [frag(m).f1_macro - rag(m).f1_macro for m in MODELS]
    P(f"- At each method's best k (filtered RAG k {'/'.join(kstr(frag(m)) for m in MODELS)} vs RAG k "
      f"{'/'.join(kstr(rag(m)) for m in MODELS)}): {', '.join(pts(x) for x in d)}; range {prng(d)} points.")
    P("- Per-model 95% CIs of filtered RAG minus RAG at best k — **from the draft** (1,000 paired "
      "resamples per model): 3B [+0.2, +3.0], 7B [+0.7, +3.2], 14B [+1.4, +3.4], 32B [+0.7, +2.2] points "
      "(draft: [+0.002, +0.030], [+0.007, +0.032], [+0.014, +0.034], [+0.007, +0.022]); all exclude zero.")
    P("")
    P("Per-class change, filtered RAG minus RAG at best k (points):")
    P("")
    cols = [("Q F1", "f1_question"), ("Q P", "p_question"), ("Q R", "r_question"), ("Bug P", "p_bug"),
            ("Bug R", "r_bug"), ("Bug F1", "f1_bug"), ("Feat F1", "f1_feature"),
            ("Q→bug", "conf_question_to_bug"), ("Q→feat", "conf_question_to_feature")]
    P("| Model | " + " | ".join(c for c, _ in cols) + " |")
    P("|---|" + "---|" * len(cols))
    diffs = {c: [] for c, _ in cols}
    for m in MODELS:
        row = []
        for c, key in cols:
            x = frag(m)[key] - rag(m)[key]
            diffs[c].append(x)
            row.append(pts(x))
        P(f"| {m} | " + " | ".join(row) + " |")
    P("")
    for c, _ in cols:
        P(f"- {c}: range {prng(diffs[c])}; max |change| {100 * max(abs(x) for x in diffs[c]):.1f}.")
    r3, f3_ = rag("Qwen-3B"), frag("Qwen-3B")
    P(f"- Qwen-3B bug recall {pct(r3.r_bug)}% → {pct(f3_.r_bug)}%; bug F1 {pct(r3.f1_bug)}% → {pct(f3_.f1_bug)}% "
      f"(a drop of {100 * (r3.f1_bug - f3_.f1_bug):.1f} points).")
    P(f"- Q→bug at best k: RAG {srng([rag(m).conf_question_to_bug for m in MODELS])}; filtered RAG "
      f"{srng([frag(m).conf_question_to_bug for m in MODELS])}.")
    avg_r = [mean(cell("ragtag", "PS", m, k).conf_question_to_bug for k in KS) for m in MODELS]
    avg_f = [mean(cell("bragtag", "PS", m, k).conf_question_to_bug for k in KS) for m in MODELS]
    P(f"- Q→bug averaged over k ∈ {{1,3,6,9,12,15}}: RAG {srng(avg_r)}; filtered RAG {srng(avg_f)}.")
    P("- Queries left with no examples at k = 1 and k = 3 (the filter fires for every query there): 40% and "
      "18% — **from the draft, not recomputable here**.")
    P("- Validation-split calibration — **from the draft, not recomputable here**: mean N_bug − N_question on "
      "true-question queries −1.36 (averaged over k ∈ [1, 15]); sweep m ∈ {1..5}, capped at the 95th "
      "percentile (5); m = 3 fires for 89.1% of true-question and 56.7% of true-bug queries.")
    P("")


def sec_rq3():
    P("## 4. RQ3 (fine-tuning)")
    P("")
    a = [rag(m).f1_macro - ftps(m).f1_macro for m in MODELS]
    b = [frag(m).f1_macro - ftps(m).f1_macro for m in MODELS]
    c = [ftpa(m).f1_macro - ftps(m).f1_macro for m in MODELS]
    P(f"- Same data (PS): RAG minus fine-tuning PS: {', '.join(pts(x) for x in a)}; range {prng(a)} points.")
    P(f"- Same data (PS): filtered RAG minus fine-tuning PS: {', '.join(pts(x) for x in b)}; range {prng(b)}.")
    P(f"- Fine-tuning PA minus PS: {', '.join(pts(x) for x in c)}; range {prng(c)}.")
    r32ps, r32pa = ftps("Qwen-32B"), ftpa("Qwen-32B")
    P(f"- Qwen-32B fine-tuning PS → PA: bug recall {pct(r32ps.r_bug)} → {pct(r32pa.r_bug)}; question recall "
      f"{pct(r32ps.r_question)} → {pct(r32pa.r_question)}.")
    P("")
    P("Differences from PA fine-tuning, paired bootstrap 95% CI (points; `method_comparison_ci.csv`, "
      "1,000 issue-level resamples; bold in Table II = CI excludes zero):")
    P("")
    ci = pd.read_csv(CI, comment="#", dtype={"k": str})
    P("| Method | Protocol | " + " | ".join(MODELS + ["All (mean)"]) + " |")
    P("|---|---|" + "---|" * 5)
    for method in ("ragtag", "bragtag"):
        for proto in ("raw", "fallback"):
            row = []
            for m in MODELS + ["All"]:
                r = ci[(ci.method == method) & (ci.protocol == proto) & (ci.model == m)].iloc[0]
                ex = " ✱" if (r.ci_lo > 0 or r.ci_hi < 0) else ""
                row.append(f"{pts(r.delta)} [{pts(r.ci_lo)}, {pts(r.ci_hi)}]{ex}")
            P(f"| {NAMES[method]} | {proto} | " + " | ".join(row) + " |")
    P("")
    P("✱ = the CI excludes zero. \"fallback\": invalid outputs of both methods labeled by kNN voting "
      "(PS k = 15 for RAG/filtered RAG, PA k = 16 for fine-tuning).")
    fr = ci[(ci.method == "bragtag") & (ci.protocol == "raw") & (ci.model != "All")].delta
    ff = ci[(ci.method == "bragtag") & (ci.protocol == "fallback") & (ci.model != "All")].delta
    P(f"- Filtered RAG minus fine-tuning PA per size, raw: range {prng(fr)}; with fallback: range {prng(ff)}.")
    P("")
    P("Fixed-k gaps, method (PS, fixed k) minus fine-tuning PA (points):")
    P("")
    P("| Method | k | " + " | ".join(MODELS) + " | mean |")
    P("|---|---|" + "---|" * 5)
    for method in ("bragtag", "ragtag"):
        for k in (6, 9, 12, 15):
            d = [cell(method, "PS", m, k).f1_macro - ftpa(m).f1_macro for m in MODELS]
            P(f"| {NAMES[method]} | {k} | " + " | ".join(pts(x) for x in d) + f" | {pts(mean(d))} |")
    P("")
    P("Error profile at the compared configurations:")
    P("")
    P("| Method | " + " | ".join(MODELS) + " | range |")
    P("|---|" + "---|" * 5)
    for label, fn, key, f in (("FT PA predicted bug share", ftpa, "share_bug", share),
                              ("Filtered RAG predicted bug share", frag, "share_bug", share),
                              ("FT PA bug recall", ftpa, "r_bug", pct),
                              ("Filtered RAG bug recall", frag, "r_bug", pct),
                              ("FT PA bug precision", ftpa, "p_bug", pct),
                              ("Filtered RAG bug precision", frag, "p_bug", pct),
                              ("FT PA Q→bug", ftpa, "conf_question_to_bug", share),
                              ("Filtered RAG Q→bug", frag, "conf_question_to_bug", share),
                              ("FT PA false bug predictions (share of all issues)", ftpa, None, share),
                              ("Filtered RAG false bug predictions (share of all issues)", frag, None, share)):
        if key is None:
            vals = [(fn(m).conf_question_to_bug + fn(m).conf_feature_to_bug) / 3 for m in MODELS]
        else:
            vals = [fn(m)[key] for m in MODELS]
        r = srng(vals) if f is share else rng(vals)
        P(f"| {label} | " + " | ".join(f(v) for v in vals) + f" | {r} |")
    P("")
    fewer = [m for m in MODELS if (frag(m).conf_question_to_bug + frag(m).conf_feature_to_bug)
             < (ftpa(m).conf_question_to_bug + ftpa(m).conf_feature_to_bug)]
    P(f"- Sizes where filtered RAG makes fewer false bug predictions than FT PA: {', '.join(fewer)}.")
    P(f"- Sizes where FT PA has higher bug recall: "
      f"{', '.join(m for m in MODELS if ftpa(m).r_bug > frag(m).r_bug)}.")
    P("- True bug share of the test set: 33% (1,100 of 3,300).")
    for m in ("Qwen-7B", "Qwen-14B"):
        P(f"- {m}: filtered RAG macro recall minus FT PA {pts(frag(m).r_macro - ftpa(m).r_macro)}; macro "
          f"precision {pts(frag(m).p_macro - ftpa(m).p_macro)} points.")
    dp = [abs(frag(m).p_macro - ftpa(m).p_macro) for m in MODELS]
    P(f"- |macro precision gap| filtered RAG vs FT PA, max over sizes: {100 * max(dp):.1f} points "
      f"({', '.join(pts(frag(m).p_macro - ftpa(m).p_macro) for m in MODELS)}).")
    P(f"- Invalid rate (%): RAG {rng([rag(m).invalid_rate for m in MODELS])}, filtered RAG "
      f"{rng([frag(m).invalid_rate for m in MODELS])}, FT PA {rng([ftpa(m).invalid_rate for m in MODELS])} "
      f"(max {100 * max(ftpa(m).invalid_rate for m in MODELS):.1f}).")
    inv = [frag(m).conf_bug_to_invalid for m in MODELS]
    P(f"- True bugs with invalid outputs, filtered RAG: {', '.join(share(x) for x in inv)}; at 7B and larger "
      f"{srng(inv[1:])}.")
    fb = pd.read_csv(FALLBACK, comment="#", dtype={"k": str})
    ftd = [fb[(fb.method == "finetune") & (fb.model == m)].iloc[0].f1_macro_fallback - ftpa(m).f1_macro
           for m in MODELS]
    P(f"- FT PA macro F1 change with the fallback (fallback CSV is 3 d.p.): "
      f"{', '.join(pts(x) for x in ftd)}; max |change| {100 * max(abs(x) for x in ftd):.1f} points.")
    P("")
    # cost
    tex = COST.read_text()
    rows = re.findall(r"^\s*(Qwen-\d+B|)\s*&\s*(\\\w+|Fine-Tune|Fine-tuning|[^&]+?)\s*&\s*([\d.]+)\s*&\s*"
                      r"([\d.]+|--)\s*&\s*([\d.]+|\$<\$0\.01)\s*&\s*([\d.]+|\$<\$0\.01)\s*\\\\", tex, re.M)
    cost, model = {}, None
    for mdl, meth, gb, tr, inf, tot in rows:
        model = mdl or model
        key = {"\\ragtag": "rag", "\\bragtag": "frag", "\\rag": "rag", "\\frag": "frag"}.get(meth, "ft")
        cost[(model, key)] = (float(gb), tr, inf, tot)
    P("Cost (`SANER2027/tables/method_cost.tex`; RAG memory is inference, fine-tuning memory is training plus "
      "inference):")
    P("")
    P("| Model | RAG GB | Filtered RAG GB | FT GB | Saving | RAG infer h | Filtered RAG infer h | FT train h | "
      "FT infer h | FT total h |")
    P("|---|---|---|---|---|---|---|---|---|---|")
    savings = []
    for m in MODELS:
        r, f, t = cost[(m, "rag")], cost[(m, "frag")], cost[(m, "ft")]
        s = 1 - r[0] / t[0]
        savings.append(s)
        P(f"| {m} | {r[0]} | {f[0]} | {t[0]} | {100 * s:.0f}% ({100 * s:.1f}) | {r[2]} | {f[2]} | {t[1]} | "
          f"{t[2]} | {t[3]} |")
    P("")
    P(f"- Memory saving (from the GB values in the table): {'/'.join(f'{100 * s:.0f}' for s in savings)}%; mean "
      f"{share(mean(savings))}.")
    ft_inf = [float(cost[(m, 'ft')][2]) for m in MODELS]
    fr_inf = [float(cost[(m, 'frag')][2]) for m in MODELS]
    P(f"- Inference time: fine-tuned models {min(ft_inf):.2f}–{max(ft_inf):.2f} h; filtered RAG "
      f"{min(fr_inf):.2f}–{max(fr_inf):.2f} h. Totals: filtered RAG "
      f"{', '.join(cost[(m, 'frag')][3] for m in MODELS)} h vs fine-tuning "
      f"{', '.join(cost[(m, 'ft')][3] for m in MODELS)} h.")
    P("- kNN voting (PS, k = 15): 0.2 GB peak GPU memory (242.2 MB), under 4 s (3.58 s) for the 3,300 test "
      "issues (method_cost.tex header).")
    P("")


def sec_discussion():
    P("## 5. Discussion")
    P("")
    P("- Failure analysis (Qwen-32B, 150 sampled errors, 50 per method) — **from the draft**: wrong "
      "template 116/150 = 77.3%, hybrid intent 20/150 = 13.3%, label noise 14/150 = 9.3% (the draft prints "
      "77.33/13.33/9.33%).")
    P("- Invalid outputs (60 sampled, 30 each from RAG and filtered RAG) — **from the draft**: 44/60 = 73% "
      "continued generation or reasoning, 14/60 = 23% degenerate text, 2/60 = 3% out-of-set labels.")
    v, z3 = best("votag", "PS", "-"), zs("Qwen-3B")
    P(f"- kNN voting PS ({pct(v.f1_macro)}%) vs Qwen-3B zero-shot ({pct(z3.f1_macro)}%): "
      f"{pts(z3.f1_macro - v.f1_macro)} points (zero-shot ahead); memory 0.2 GB (≈240 MB) vs 2.9 GB.")
    P("")


def sec_heatmap():
    P("## 6. Heatmap (filtered RAG PS best k minus fine-tuning PA, per project; points)")
    P("")
    P("Source `paper/tables/per_project_diff.csv` is hand-seeded at 3 d.p. (transcribed from the old figure), so "
      "the one-decimal values below inherit that rounding. One cell (ansible, Qwen-3B) is exactly 0.000; it "
      "counts as \"matches or exceeds\" (≥ 0), but its sign is unknown until the lab machine regenerates the CSV.")
    P("")
    df = pd.read_csv(PER_PROJECT, comment="#").set_index("model").loc[MODELS]
    projects = [c for c in df.columns if c != "k"]
    P("| Project | " + " | ".join(MODELS) + " |")
    P("|---|" + "---|" * 4)
    for p in projects:
        P(f"| {p} | " + " | ".join(pts(df.loc[m, p]) for m in MODELS) + " |")
    vals = df[projects].values.flatten()
    P("")
    P(f"- Cells ≥ 0: {(vals >= 0).sum()} of {vals.size}; cells > 0: {(vals > 0).sum()}; cells exactly 0.000: "
      f"{(vals == 0).sum()}.")
    for p in projects:
        n = (df[p] >= 0).sum()
        if n >= 3:
            P(f"- {p}: ≥ 0 at {n} of 4 sizes.")
    P("")


def main() -> None:
    header()
    sec_best()
    sec_rq1()
    sec_rq2()
    sec_rq3()
    sec_discussion()
    sec_heatmap()
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
