"""SANER2027/tables/method_comparison_ci.tex -- Table II of Section V: macro-F1
differences from PA fine-tuning with paired bootstrap 95% CIs, raw and with the
VOTAG fallback for invalid outputs (the RQ4 secondary protocol), interleaved per
model, plus "All sizes".

Reads paper/tables/method_comparison_ci.csv, written by
scripts/paper/significance_method_comparison.py on the lab machine. Layout: one
raw row and one +VOTAG row per model (and for "All sizes"), so the fallback's
effect is read directly; a delta whose CI excludes zero is bold; a missing CI
prints as "--".
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from _figstyle import MODELS

REPO = Path(__file__).resolve().parents[2]
CSV = REPO / "paper" / "tables" / "method_comparison_ci.csv"
OUT = REPO / "SANER2027" / "tables" / "method_comparison_ci.tex"

PROTOCOLS = [("raw", None), ("fallback", r"\quad +\votag")]


def fd(x: float, bold: bool) -> str:
    v = f"{x:+.3f}"
    return rf"$\mathbf{{{v}}}$" if bold else f"${v}$"


def fci(lo, hi) -> str:
    if pd.isna(lo) or pd.isna(hi):
        return "--"
    return f"$[{lo:+.3f}, {hi:+.3f}]$"


def _row(df, method, protocol, model):
    q = df[(df.method == method) & (df.protocol == protocol) & (df.model == model)]
    if len(q) != 1:
        raise SystemExit(f"missing row: {method} {protocol} {model}")
    return q.iloc[0]


def _cell(df, method, protocol, model):
    r = _row(df, method, protocol, model)
    significant = not (pd.isna(r.ci_lo) or pd.isna(r.ci_hi)) and (r.ci_lo > 0 or r.ci_hi < 0)
    return f"{fd(r.delta, significant)} & {fci(r.ci_lo, r.ci_hi)}"


def emit(df: pd.DataFrame) -> str:
    """Interleaved layout (author request, 2026-09-22): every model has a raw row
    followed by its +VOTAG row, so the fallback's effect is read top-to-bottom;
    a bold delta has a CI that excludes zero."""
    L = [
        "% Generated by scripts/paper/tab_method_comparison_ci.py from paper/tables/method_comparison_ci.csv",
        "% -- do not edit by hand. See the CSV header for the provenance of the current numbers.",
        r"\begin{table}[!t]",
        r"  \centering",
        r"  \caption{Macro-$F_1$ difference from PA fine-tuning without and with the \votag\ fallback "
        r"(paired bootstrap 95\% CI).}",
        r"  \label{tab:method-comparison-ci}",
        r"  \footnotesize",
        r"  \setlength{\tabcolsep}{3pt}",
        r"  \begin{tabular}{@{}lrlrl@{}}",
        r"    \toprule",
        r"     & \multicolumn{2}{c}{\ragtag\ $-$ Fine-Tune} & \multicolumn{2}{c}{\bragtag\ $-$ Fine-Tune} \\",
        r"    \cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"    Model & $\Delta F_1$ & 95\% CI & $\Delta F_1$ & 95\% CI \\",
        r"    \midrule",
    ]
    for i, m in enumerate(MODELS + ["All"]):
        if m == "All":
            L.append(r"    \midrule")
        elif i:
            L.append(r"    \addlinespace[1.5pt]")
        for protocol, sublabel in PROTOCOLS:
            label = sublabel if sublabel else ("All sizes" if m == "All" else m)
            L.append(f"    {label} & {_cell(df, 'ragtag', protocol, m)} & {_cell(df, 'bragtag', protocol, m)} \\\\")
    L += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"  \par\vspace{2pt}",
        r"  \parbox{\columnwidth}{\scriptsize \ragtag/\bragtag\ under PS at their best $k$, fine-tuning under PA; "
        r"negative values favor fine-tuning. Each +\votag\ row applies the \votag\ fallback for invalid outputs "
        r"to both methods (\votag-PS at $k{=}15$ for \ragtag/\bragtag, \votag-PA at $k{=}16$ for fine-tuning). "
        r"Bold: CI excludes zero. All sizes: mean of the four per-model differences.}",
        r"\end{table}",
        "",
    ]
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--csv", type=Path, default=CSV)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()
    df = pd.read_csv(args.csv, comment="#", dtype={"k": str})
    args.out.write_text(emit(df))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
